DROP TABLE IF EXISTS TEMPLATE_S;
DROP TABLE IF EXISTS JOB_S;

CREATE TABLE TEMPLATE_S (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Customer_name TEXT NOT NULL,
  Template_Id TEXT UNIQUE NOT NULL,
  Description_ TEXT NOT NULL
--   OS_type TEXT NOT NULL,
--   Product_family TEXT NOT NULL,
--   Command TEXT NOT NULL,
--   WLE TEXT NOT NULL,
--   BLE TEXT NOT NULL,
--   Report_format TEXT NOT NULL,
--   DCP_upload TEXT NOT NULL,
--   SR_creation TEXT NOT NULL
);

CREATE TABLE JOB_S (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Customer_name TEXT NOT NULL,
  Template_Id TEXT NOT NULL
);